import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';
import { CookiesProvider } from 'next-client-cookies/server';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from 'sonner';

import { ThemeProvider } from '@/components/theme-provider';
import TimeZoneSetter from '@/components/time-zone-setter';
import NextTopLoader from '@/components/top-loader';
import { TRPCReactProvider } from '@/server/react';

import type { Metadata } from 'next';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Expense Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NuqsAdapter>
          <CookiesProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              disableTransitionOnChange
              enableSystem
            >
              <NextTopLoader />
              <TRPCReactProvider>{children}</TRPCReactProvider>
              <Toaster />
              <TimeZoneSetter />
            </ThemeProvider>
          </CookiesProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
